#!/bin/sh

# colo <char>

a0='[30m'; a1='[31m'; a2='[32m'; a3='[33m'
a4='[34m'; a5='[35m'; a6='[36m'; a7='[37m'

b0='[1;30m'; b1='[1;31m'; b2='[1;32m'; b3='[1;33m'
b4='[1;34m'; b5='[1;35m'; b6='[1;36m'; b7='[1;37m'

rst='[0m'
char=$1
c=$char$char$char

cat << COLOS

 $a0$c $a1$c $a2$c $a3$c $a4$c $a5$c $a6$c $a7$c$rst
 $b0$c $b1$c $b2$c $b3$c $b4$c $b5$c $b6$c $b7$c$rst

COLOS
